# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HST Experience
email: m@kevan.tv
description: >
  HST Experience
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

  
gems:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - /vendor

mini_magick:
  thumbnail: # Preset name
    source: images # source directory - change this to whatever you want
    destination: images/thumbnails # generated destination directory
    resize: "600x400^" # standard imagemagick options - you can chain multiple commands
    gravity: "center"
    extent: "600x400"
  cover: # Preset name
    source: images # source directory - change this to whatever you want
    destination: images/covers # generated destination directory
    resize: "1200x600^" # standard imagemagick options - you can chain multiple commands
    gravity: "center"
    extent: "1200x600"
  profiles: # Preset name
    source: images # source directory - change this to whatever you want
    destination: images/profiles # generated destination directory
    resize: "600x600^" # standard imagemagick options - you can chain multiple commands
    gravity: "center"
    extent: "600x600"
    colorspace: "gray"

collections:
  articles:
    output: true
    permalink: /articles/:path/
  categories:
    output: true
    permalink: /:path/
  profiles:
    output: true
    permalink: /the-team/:path/

defaults:
  -
    scope:
      path: ""
      type: "articles"
    values: 
      layout: "post"
      description: ""
      tags: []
  -
    scope:
      path: ""
      type: "categories"
    values: 
      layout: "category"
      description: ""
      tags: []
  -
    scope:
      path: ""
      type: "profiles"
    values: 
      layout: "post"
      description: ""
      tags: []